spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.as.commonevents.events"
        spring.json.type.mapping: >
          tripRequested:com.as.commonevents.events.TripRequestedEvent,
          driverAssigned:com.as.commonevents.events.DriverAssignedEvent,
          driverAccepted:com.as.commonevents.events.DriverAcceptedEvent,
          driverArrived:com.as.commonevents.events.DriverArrivedEvent,
          tripStarted:com.as.commonevents.events.TripStarted,
          tripCompleted:com.as.commonevents.events.TripCompleted,
          driverLocationUpdated:com.as.commonevents.events.DriverLocationUpdatedEvent,
          driverEtaUpdated:com.as.commonevents.events.DriverEtaUpdatedEvent


server:
  port: 8090

