spring:
  application:
    name: location-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: location-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#          spring.json.value.default.type: com.as.commonevents.events.DriverLocationUpdatedEvent
          spring.json.trusted.packages: "com.as.commonevents.events"
          spring.json.use.type.headers: true
          spring.json.type.mapping: >
            driverRegistered:com.as.commonevents.events.DriverRegisteredEvent,
            driverStatusUpdated:com.as.commonevents.events.DriverStatusUpdatedEvent



server:
  port: 8082
